from __future__ import annotations

ACCREDITATION_VALUES: frozenset[str] = frozenset(
    {
        "accredited",
        "unaccredited",
    }
)

GOVERNANCE_VALUES: frozenset[str] = frozenset(
    {
        "national",
        "local authority",
        "other government",
        "university",
        "independent: not-for-profit",
        "independent: English Heritage",
        "independent: National Trust",
        "independent: National Trust for Scotland",
        "independent: Historic Environment Scotland",
        "private",
        "unknown governance",
    }
)

SIZE_VALUES: frozenset[str] = frozenset(
    {
        "huge",
        "large",
        "medium",
        "small",
        "unknown size",
    }
)

SUBJECT_VALUES: frozenset[str] = frozenset(
    {
        "archaeology",
        "archaeology: greek & egyptian",
        "archaeology: medieval",
        "archaeology: mixed",
        "archaeology: other",
        "archaeology: prehistory",
        "archaeology: roman",
        "arts",
        "arts: ceramics",
        "arts: costume & textiles",
        "arts: crafts",
        "arts: design",
        "arts: fine & decorative arts",
        "arts: glass",
        "arts: literature",
        "arts: music",
        "arts: other",
        "arts: photography",
        "belief & identity",
        "belief & identity: church treasuries",
        "belief & identity: ethnic group",
        "belief & identity: freemasons",
        "belief & identity: other",
        "belief & identity: religion",
        "belief & identity: religious buildings",
        "buildings",
        "buildings: civic",
        "buildings: houses (large)",
        "buildings: houses (medium)",
        "buildings: houses (small)",
        "buildings: other",
        "buildings: palace",
        "buildings: penal",
        "buildings: school",
        "buildings: shops",
        "communications",
        "communications: other",
        "communications: post",
        "communications: radio",
        "food & drink",
        "industry & manufacture",
        "industry & manufacture: clocks & watches",
        "industry & manufacture: industrial life",
        "industry & manufacture: metals",
        "industry & manufacture: mining & quarrying",
        "industry & manufacture: mixed",
        "industry & manufacture: other",
        "industry & manufacture: potteries",
        "industry & manufacture: print",
        "industry & manufacture: steam & engines",
        "industry & manufacture: textiles",
        "leisure & sport",
        "leisure & sport: cricket",
        "leisure & sport: fairgrounds & amusements",
        "leisure & sport: film cinema & tv",
        "leisure & sport: other",
        "leisure & sport: rugby & football",
        "leisure & sport: toys & models",
        "local histories",
        "medicine & health",
        "medicine & health: hospital",
        "medicine & health: other",
        "medicine & health: professional association",
        "mixed",
        "mixed: bygones",
        "mixed: encyclopaedic",
        "mixed: other",
        "natural world",
        "natural world: dinosaurs",
        "natural world: fossils",
        "natural world: geology",
        "natural world: herbaria & gardening",
        "natural world: mixed",
        "natural world: other",
        "natural world: zoology",
        "other",
        "personality",
        "personality: art",
        "personality: explorer",
        "personality: literary",
        "personality: music",
        "personality: other",
        "personality: political",
        "personality: religious",
        "personality: scientific",
        "rural industry",
        "rural industry: farming",
        "rural industry: forges",
        "rural industry: other",
        "rural industry: rural life",
        "rural industry: textiles",
        "rural industry: watermills",
        "rural industry: windmills",
        "science & technology",
        "science & technology: computing & gaming",
        "science & technology: other",
        "sea & seafaring",
        "sea & seafaring: boats & ships",
        "sea & seafaring: fishing",
        "sea & seafaring: lighthouses",
        "sea & seafaring: mixed",
        "sea & seafaring: other",
        "services",
        "services: fire",
        "services: other",
        "services: police",
        "services: rnli",
        "transport",
        "transport: aviation",
        "transport: bicycles",
        "transport: buses & trams",
        "transport: canals",
        "transport: cars & motorbikes",
        "transport: mixed",
        "transport: other",
        "transport: trains & railways",
        "utilities",
        "utilities: gas & electricity",
        "utilities: water & waste",
        "war & conflict",
        "war & conflict: airforce",
        "war & conflict: bunker",
        "war & conflict: castles & forts",
        "war & conflict: event or site",
        "war & conflict: military",
        "war & conflict: navy",
        "war & conflict: other",
        "war & conflict: regiment",
    }
)
