tidy_labels_size <- c(
  "unknown"="Unknown size",
  "small"="Small",
  "medium"="Medium",
  "large"="Large",
  "huge"="Huge"
)
size_labels <- data.frame(
  internal_label=c("unknown", "small", "medium", "large", "huge"),
  tidy_label=c("Unknown size", "Small", "Medium", "Large", "Huge"),
  default_filter=c(TRUE, TRUE, TRUE, TRUE, TRUE)
)

tidy_labels_governance <- c(
  "Unknown"="Unknown governance",
  "Private"="Private",
  "Independent"="Independent",
  "Independent-Not_for_profit"="Not for Profit",
  "Independent-National_Trust_for_Scotland"="National Trust Scot.",
  "Independent-National_Trust"="National Trust",
  "Independent-English_Heritage"="English Heritage",
  "Independent-Historic_Environment_Scotland"="Historic Environment Scot.",
  "University"="University",
  "Other_Government"="Other Government",
  "Local_Authority"="Local Authority",
  "National"="National"
)
governance_labels <- data.frame(
  internal_label=c(
    "Unknown",
    "Private",
    "Independent",
    "Independent-Not_for_profit",
    "Independent-National_Trust_for_Scotland",
    "Independent-National_Trust",
    "Independent-English_Heritage",
    "Independent-Historic_Environment_Scotland",
    "University",
    "Other_Government",
    "Local_Authority",
    "National"
  ),
  tidy_label=c(
    "Unknown governance",
    "Private",
    "Independent",
    "Not for Profit",
    "National Trust Scot.",
    "National Trust",
    "English Heritage",
    "Historic Environment Scot.",
    "University",
    "Other Government",
    "Local Authority",
    "National"
  ),
  default_filter=c(
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE
  ),
  is_broad_type=c(
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    TRUE
  )
)

governance_choices <- setNames(names(tidy_labels_governance), tidy_labels_governance)
governance_to_sector <- c(
  "Unknown"="unknown",
  "Private"="private",
  "Independent"="third",
  "Independent-Not_for_profit"="third",
  "Independent-National_Trust_for_Scotland"="third",
  "Independent-National_Trust"="third",
  "Independent-English_Heritage"="third",
  "Independent-Historic_Environment_Scotland"="third",
  "University"="university",
  "Other_Government"="public",
  "Local_Authority"="public",
  "National"="public"
)

tidy_labels_country_region <- c(
    "Isle of Man"="Isle of Man",
    "Channel Islands"="Channel Islands",
    "Northern Ireland"="Northern Ireland",
    "Wales"="Wales",
    "Scotland"="Scotland",
    "England"="England",
    "North East (English Region)"="North East",
    "North West (English Region)"="North West",
    "Yorkshire and The Humber (English Region)"="Yorks & Humber",
    "East Midlands (English Region)"="East Midlands",
    "West Midlands (English Region)"="West Midlands",
    "East of England (English Region)"="East of England",
    "London (English Region)"="London",
    "South East (English Region)"="South East",
    "South West (English Region)"="South West"
)
country_region_labels <- data.frame(
  internal_label=c(
    "Isle of Man",
    "Channel Islands",
    "Northern Ireland",
    "Wales",
    "Scotland",
    "England",
    "North East (English Region)",
    "North West (English Region)",
    "Yorkshire and The Humber (English Region)",
    "East Midlands (English Region)",
    "West Midlands (English Region)",
    "East of England (English Region)",
    "London (English Region)",
    "South East (English Region)",
    "South West (English Region)"
  ),
  tidy_label=c(
    "Isle of Man",
    "Channel Islands",
    "Northern Ireland",
    "Wales",
    "Scotland",
    "England",
    "North East",
    "North West",
    "Yorks & Humber",
    "East Midlands",
    "West Midlands",
    "East of England",
    "London",
    "South East",
    "South West"
  ),
  default_filter=c(
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE
  )
)

tidy_labels_accreditation <- c(
    "Accredited"="Accredited",
    "Unaccredited"="Unaccredited"
)
accreditation_labels <- data.frame(
  internal_label=c("Accredited", "Unaccredited"),
  tidy_label=c("Accredited", "Unaccredited"),
  default_filter=c(TRUE, TRUE)
)

tidy_labels_subject <- c(
  "War_and_conflict"="War & Conflict",
  "Utilities"="Utilities",
  "Transport"="Transport",
  "Services"="Services",
  "Sea_and_seafaring"="Sea & Seafaring",
  "Science_and_technology"="Science & Technology",
  "Rural_Industry"="Rural Industry",
  "Personality"="Personality",
  "Other"="Other",
  "Natural_world"="Natural World",
  "Mixed"="Mixed",
  "Medicine_and_health"="Medicine & Health",
  "Local_Histories"="Local Histories",
  "Leisure_and_sport"="Leisure & Sport",
  "Industry_and_manufacture"="Industry & Manufacture",
  "Food_and_drink"="Food & Drink",
  "Communications"="Communications",
  "Buildings"="Buildings",
  "Belief_and_identity"="Belief & Identity",
  "Arts"="Arts",
  "Archaeology"="Archaeology"
)
subject_broad_labels <- data.frame(
  internal_label=c(
    "War_and_conflict",
    "Utilities",
    "Transport",
    "Services",
    "Sea_and_seafaring",
    "Science_and_technology",
    "Rural_Industry",
    "Personality",
    "Other",
    "Natural_world",
    "Mixed",
    "Medicine_and_health",
    "Local_Histories",
    "Leisure_and_sport",
    "Industry_and_manufacture",
    "Food_and_drink",
    "Communications",
    "Buildings",
    "Belief_and_identity",
    "Arts",
    "Archaeology"
  ),
  tidy_label=c(
    "War & Conflict",
    "Utilities",
    "Transport",
    "Services",
    "Sea & Seafaring",
    "Science & Technology",
    "Rural Industry",
    "Personality",
    "Other",
    "Natural World",
    "Mixed",
    "Medicine & Health",
    "Local Histories",
    "Leisure & Sport",
    "Industry & Manufacture",
    "Food & Drink",
    "Communications",
    "Buildings",
    "Belief & Identity",
    "Arts",
    "Archaeology"
  ),
  default_filter=c(
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE
  )
)

tidy_labels_subject_full <- c(
  "Archaeology-Greek_and_Egyptian"="Archaeology: Greek & Egyptian",
  "Archaeology-Medieval"="Archaeology: Medieval",
  "Archaeology-Prehistory"="Archaeology: Prehistory",
  "Archaeology-Roman"="Archaeology: Roman",
  "Archaeology-Mixed"="Archaeology: Mixed",
  "Archaeology-Other"="Archaeology: Other",
  "Arts-Ceramics"="Arts: Ceramics",
  "Arts-Costume_and_textiles"="Arts: Costume & Textiles",
  "Arts-Crafts"="Arts: Crafts",
  "Arts-Design"="Arts: Design",
  "Arts-Fine_and_decorative_arts"="Arts: Fine & Decorative Arts",
  "Arts-Glass"="Arts: Glass",
  "Arts-Literature"="Arts: Literature",
  "Arts-Music"="Arts: Music",
  "Arts-Photography"="Arts: Photography",
  "Arts-Other"="Arts: Other",
  "Belief_and_identity-Church_treasuries"="Belief & Identity: Church Treasuries",
  "Belief_and_identity-Ethnic_group"="Belief & Identity: Ethnic Group",
  "Belief_and_identity-Freemasons"="Belief & Identity: Freemasons",
  "Belief_and_identity-Religion"="Belief & Identity: Religion",
  "Belief_and_identity-Religious_buildings"="Belief & Identity: Religious Buildings",
  "Belief_and_identity-Other"="Belief & Identity: Other",
  "Buildings-Civic"="Buildings: Civic",
  "Buildings-Houses-Large_houses"="Buildings: Houses (Large)",
  "Buildings-Houses-Medium_houses"="Buildings: Houses (Medium)",
  "Buildings-Houses-Small_houses"="Buildings: Houses (Small)",
  "Buildings-Palace"="Buildings: Palace",
  "Buildings-Penal"="Buildings: Penal",
  "Buildings-School"="Buildings: School",
  "Buildings-Shops"="Buildings: Shops",
  "Buildings-Other"="Buildings: Other",
  "Communications-Post"="Communications: Post",
  "Communications-Radio"="Communications: Radio",
  "Communications-Other"="Communications: Other",
  "Industry_and_manufacture-Clocks_and_watches"="Industry & Manufacture: Clocks & Watches",
  "Industry_and_manufacture-Industrial_life"="Industry & Manufacture: Industrial Life",
  "Industry_and_manufacture-Metals"="Industry & Manufacture: Metals",
  "Industry_and_manufacture-Mining_and_quarrying"="Industry & Manufacture: Mining & Quarrying",
  "Industry_and_manufacture-Potteries"="Industry & Manufacture: Potteries",
  "Industry_and_manufacture-Print"="Industry & Manufacture: Print",
  "Industry_and_manufacture-Steam_and_engines"="Industry & Manufacture: Steam & Engines",
  "Industry_and_manufacture-Textiles"="Industry & Manufacture: Textiles",
  "Industry_and_manufacture-Mixed"="Industry & Manufacture: Mixed",
  "Industry_and_manufacture-Other"="Industry & Manufacture: Other",
  "Leisure_and_sport-Cricket"="Leisure & Sport: Cricket",
  "Leisure_and_sport-Fairgrounds_and_amusements"="Leisure & Sport: Fairgrounds & Amusements",
  "Leisure_and_sport-Film_Cinema_and_TV"="Leisure & Sport: Film, Cinema & TV",
  "Leisure_and_sport-Rugby_and_football"="Leisure & Sport: Rugby & Football",
  "Leisure_and_sport-Toys_and_models"="Leisure & Sport: Toys & Models",
  "Leisure_and_sport-Other"="Leisure & Sport: Other",
  "Medicine_and_health-Hospital"="Medicine & Health: Hospital",
  "Medicine_and_health-Professional_association"="Medicine & Health: Professional Association",
  "Medicine_and_health-Other"="Medicine & Health: Other",
  "Natural_world-Dinosaurs"="Natural World: Dinosaurs",
  "Natural_world-Fossils"="Natural World: Fossils",
  "Natural_world-Geology"="Natural World: Geology",
  "Natural_world-Herbaria_and_gardening"="Natural World: Herbaria & Gardening",
  "Natural_world-Zoology"="Natural World: Zoology",
  "Natural_world-Mixed"="Natural World: Mixed",
  "Natural_world-Other"="Natural World: Other",
  "Personality-Art"="Personality: Art",
  "Personality-Explorer"="Personality: Explorer",
  "Personality-Literary"="Personality: Literary",
  "Personality-Music"="Personality: Music",
  "Personality-Political"="Personality: Political",
  "Personality-Religious"="Personality: Religious",
  "Personality-Scientific"="Personality: Scientific",
  "Personality-Other"="Personality: Other",
  "Rural_Industry-Farming"="Rural Industry: Farming",
  "Rural_Industry-Forges"="Rural Industry: Forges",
  "Rural_Industry-Rural_life"="Rural Industry: Rural Life",
  "Rural_Industry-Textiles"="Rural Industry: Textiles",
  "Rural_Industry-Watermills"="Rural Industry: Watermills",
  "Rural_Industry-Windmills"="Rural Industry: Windmills",
  "Rural_Industry-Other"="Rural Industry: Other",
  "Science_and_technology-Computing_and_gaming"="Science & Technology: Computing & Gaming",
  "Science_and_technology-Other"="Science & Technology: Other",
  "Sea_and_seafaring-Boats_and_ships"="Sea & Seafaring: Boats & Ships",
  "Sea_and_seafaring-Fishing"="Sea & Seafaring: Fishing",
  "Sea_and_seafaring-Lighthouses"="Sea & Seafaring: Lighthouses",
  "Sea_and_seafaring-Mixed"="Sea & Seafaring: Mixed",
  "Sea_and_seafaring-Other"="Sea & Seafaring: Other",
  "Services-Fire"="Services: Fire",
  "Services-Police"="Services: Police",
  "Services-RNLI"="Services: RNLI",
  "Services-Other"="Services: Other",
  "Transport-Aviation"="Transport: Aviation",
  "Transport-Bicycles"="Transport: Bicycles",
  "Transport-Buses_and_trams"="Transport: Buses & Trams",
  "Transport-Canals"="Transport: Canals",
  "Transport-Cars_and_motorbikes"="Transport: Cars & Motorbikes",
  "Transport-Trains_and_railways"="Transport: Trains & Railways",
  "Transport-Mixed"="Transport: Mixed",
  "Transport-Other"="Transport: Other",
  "Utilities-Gas_and_electricity"="Utilities: Gas & Electricity",
  "Utilities-Water_and_waste"="Utilities: Water & Waste",
  "War_and_conflict-Airforce"="War & Conflict: Airforce",
  "War_and_conflict-Bunker"="War & Conflict: Bunker",
  "War_and_conflict-Castles_and_forts"="War & Conflict: Castles & Forts",
  "War_and_conflict-Event_or_site"="War & Conflict: Event or Site",
  "War_and_conflict-Military"="War & Conflict: Military",
  "War_and_conflict-Navy"="War & Conflict: Navy",
  "War_and_conflict-Regiment"="War & Conflict: Regiment",
  "War_and_conflict-Other"="War & Conflict: Other",
  "Mixed-Bygones"="Mixed: Bygones",
  "Mixed-Encyclopaedic"="Mixed: Encyclopaedic",
  "Mixed-Other"="Mixed: Other"
)

subject_full_labels <- data.frame(
  internal_label=c(
    "Archaeology-Greek_and_Egyptian",
    "Archaeology-Medieval",
    "Archaeology-Prehistory",
    "Archaeology-Roman",
    "Archaeology-Mixed",
    "Archaeology-Other",
    "Archaeology",
    "Arts-Ceramics",
    "Arts-Costume_and_textiles",
    "Arts-Crafts",
    "Arts-Design",
    "Arts-Fine_and_decorative_arts",
    "Arts-Glass",
    "Arts-Literature",
    "Arts-Music",
    "Arts-Photography",
    "Arts-Other",
    "Belief_and_identity-Church_treasuries",
    "Belief_and_identity-Ethnic_group",
    "Belief_and_identity-Freemasons",
    "Belief_and_identity-Religion",
    "Belief_and_identity-Religious_buildings",
    "Belief_and_identity-Other",
    "Belief_and_identity",
    "Buildings-Civic",
    "Buildings-Houses-Large_houses",
    "Buildings-Houses-Medium_houses",
    "Buildings-Houses-Small_houses",
    "Buildings-Palace",
    "Buildings-Penal",
    "Buildings-School",
    "Buildings-Shops",
    "Buildings-Other",
    "Communications-Post",
    "Communications-Radio",
    "Communications-Other",
    "Communications",
    "Food_and_drink",
    "Industry_and_manufacture-Clocks_and_watches",
    "Industry_and_manufacture-Industrial_life",
    "Industry_and_manufacture-Metals",
    "Industry_and_manufacture-Mining_and_quarrying",
    "Industry_and_manufacture-Potteries",
    "Industry_and_manufacture-Print",
    "Industry_and_manufacture-Steam_and_engines",
    "Industry_and_manufacture-Textiles",
    "Industry_and_manufacture-Mixed",
    "Industry_and_manufacture-Other",
    "Leisure_and_sport-Cricket",
    "Leisure_and_sport-Fairgrounds_and_amusements",
    "Leisure_and_sport-Film_Cinema_and_TV",
    "Leisure_and_sport-Rugby_and_football",
    "Leisure_and_sport-Toys_and_models",
    "Leisure_and_sport-Other",
    "Local_Histories",
    "Medicine_and_health-Hospital",
    "Medicine_and_health-Professional_association",
    "Medicine_and_health-Other",
    "Natural_world-Dinosaurs",
    "Natural_world-Fossils",
    "Natural_world-Geology",
    "Natural_world-Herbaria_and_gardening",
    "Natural_world-Zoology",
    "Natural_world-Mixed",
    "Natural_world-Other",
    "Natural_world",
    "Personality-Art",
    "Personality-Explorer",
    "Personality-Literary",
    "Personality-Music",
    "Personality-Political",
    "Personality-Religious",
    "Personality-Scientific",
    "Personality-Other",
    "Rural_Industry-Farming",
    "Rural_Industry-Forges",
    "Rural_Industry-Rural_life",
    "Rural_Industry-Textiles",
    "Rural_Industry-Watermills",
    "Rural_Industry-Windmills",
    "Rural_Industry-Other",
    "Science_and_technology-Computing_and_gaming",
    "Science_and_technology-Other",
    "Sea_and_seafaring-Boats_and_ships",
    "Sea_and_seafaring-Fishing",
    "Sea_and_seafaring-Lighthouses",
    "Sea_and_seafaring-Mixed",
    "Sea_and_seafaring-Other",
    "Services-Fire",
    "Services-Police",
    "Services-RNLI",
    "Services-Other",
    "Transport-Aviation",
    "Transport-Bicycles",
    "Transport-Buses_and_trams",
    "Transport-Canals",
    "Transport-Cars_and_motorbikes",
    "Transport-Trains_and_railways",
    "Transport-Mixed",
    "Transport-Other",
    "Utilities-Gas_and_electricity",
    "Utilities-Water_and_waste",
    "War_and_conflict-Airforce",
    "War_and_conflict-Bunker",
    "War_and_conflict-Castles_and_forts",
    "War_and_conflict-Event_or_site",
    "War_and_conflict-Military",
    "War_and_conflict-Navy",
    "War_and_conflict-Regiment",
    "War_and_conflict-Other",
    "Mixed-Bygones",
    "Mixed-Encyclopaedic",
    "Mixed-Other",
    "Mixed",
    "Other"
  ),
  tidy_label=c(
    "Archaeology: Greek & Egyptian",
    "Archaeology: Medieval",
    "Archaeology: Prehistory",
    "Archaeology: Roman",
    "Archaeology: Mixed",
    "Archaeology: Other",
    "Archaeology",
    "Arts: Ceramics",
    "Arts: Costume & Textiles",
    "Arts: Crafts",
    "Arts: Design",
    "Arts: Fine & Decorative Arts",
    "Arts: Glass",
    "Arts: Literature",
    "Arts: Music",
    "Arts: Photography",
    "Arts: Other",
    "Belief & Identity: Church Treasuries",
    "Belief & Identity: Ethnic Group",
    "Belief & Identity: Freemasons",
    "Belief & Identity: Religion",
    "Belief & Identity: Religious Buildings",
    "Belief & Identity: Other",
    "Belief_and_identity",
    "Buildings: Civic",
    "Buildings: Houses (Large)",
    "Buildings: Houses (Medium)",
    "Buildings: Houses (Small)",
    "Buildings: Palace",
    "Buildings: Penal",
    "Buildings: School",
    "Buildings: Shops",
    "Buildings: Other",
    "Communications: Post",
    "Communications: Radio",
    "Communications: Other",
    "Communications",
    "Food & Drink",
    "Industry & Manufacture: Clocks & Watches",
    "Industry & Manufacture: Industrial Life",
    "Industry & Manufacture: Metals",
    "Industry & Manufacture: Mining & Quarrying",
    "Industry & Manufacture: Potteries",
    "Industry & Manufacture: Print",
    "Industry & Manufacture: Steam & Engines",
    "Industry & Manufacture: Textiles",
    "Industry & Manufacture: Mixed",
    "Industry & Manufacture: Other",
    "Leisure & Sport: Cricket",
    "Leisure & Sport: Fairgrounds & Amusements",
    "Leisure & Sport: Film, Cinema & TV",
    "Leisure & Sport: Rugby & Football",
    "Leisure & Sport: Toys & Models",
    "Leisure & Sport: Other",
    "Local Histories",
    "Medicine & Health: Hospital",
    "Medicine & Health: Professional Association",
    "Medicine & Health: Other",
    "Natural World: Dinosaurs",
    "Natural World: Fossils",
    "Natural World: Geology",
    "Natural World: Herbaria & Gardening",
    "Natural World: Zoology",
    "Natural World: Mixed",
    "Natural World: Other",
    "Natural_world",
    "Personality: Art",
    "Personality: Explorer",
    "Personality: Literary",
    "Personality: Music",
    "Personality: Political",
    "Personality: Religious",
    "Personality: Scientific",
    "Personality: Other",
    "Rural Industry: Farming",
    "Rural Industry: Forges",
    "Rural Industry: Rural Life",
    "Rural Industry: Textiles",
    "Rural Industry: Watermills",
    "Rural Industry: Windmills",
    "Rural Industry: Other",
    "Science & Technology: Computing & Gaming",
    "Science & Technology: Other",
    "Sea & Seafaring: Boats & Ships",
    "Sea & Seafaring: Fishing",
    "Sea & Seafaring: Lighthouses",
    "Sea & Seafaring: Mixed",
    "Sea & Seafaring: Other",
    "Services: Fire",
    "Services: Police",
    "Services: RNLI",
    "Services: Other",
    "Transport: Aviation",
    "Transport: Bicycles",
    "Transport: Buses & Trams",
    "Transport: Canals",
    "Transport: Cars & Motorbikes",
    "Transport: Trains & Railways",
    "Transport: Mixed",
    "Transport: Other",
    "Utilities: Gas & Electricity",
    "Utilities: Water & Waste",
    "War & Conflict: Airforce",
    "War & Conflict: Bunker",
    "War & Conflict: Castles & Forts",
    "War & Conflict: Event or Site",
    "War & Conflict: Military",
    "War & Conflict: Navy",
    "War & Conflict: Regiment",
    "War & Conflict: Other",
    "Mixed: Bygones",
    "Mixed: Encyclopaedic",
    "Mixed: Other",
    "Mixed",
    "Other"
  ),
  subject_broad=c(
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Communications",
    "Communications",
    "Communications",
    "Communications",
    "Food_and_drink",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Local_Histories",
    "Medicine_and_health",
    "Medicine_and_health",
    "Medicine_and_health",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Science_and_technology",
    "Science_and_technology",
    "Sea_and_seafaring",
    "Sea_and_seafaring",
    "Sea_and_seafaring",
    "Sea_and_seafaring",
    "Sea_and_seafaring",
    "Services",
    "Services",
    "Services",
    "Services",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Utilities",
    "Utilities",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "Mixed",
    "Mixed",
    "Mixed",
    "Mixed",
    "Other"
  )
) |>
  mutate(
    default_filter=TRUE
  )

tidy_labels <- c(
  "all"="all",
  tidy_labels_size,
  tidy_labels_governance,
  tidy_labels_country_region,
  tidy_labels_accreditation,
  tidy_labels_subject,
  tidy_labels_subject_full
)

hierarchical_filter_choices <- list(
  "Size" = unname(tidy_labels_size),
  "Governance" = unname(tidy_labels_governance),
  "Accreditation" = unname(tidy_labels_accreditation),
  "Subject" = unname(tidy_labels_subject),
  "Regions" = unname(tidy_labels_country_region)
)

short_labels <- c(
  "all"="all",
  # size
  "unknown size"="unk.",
  "small"="small",
  "medium"="med.",
  "large"="large",
  "huge"="huge",
  # governance
  "unknown governance"="unknown",
  "private"="private",
  "independent"="independent",
  "not-for-profit"="non-Profit",
  "National Trust for Scotland"="Nat Trust S",
  "National Trust"="Nat Trust",
  "English Heritage"="Eng Heritage",
  "Historic Environment Scotland"="Hist Env S",
  "university"="university",
  "other government"="other gov",
  "local authority"="local auth",
  "national"="national",
  # country / region
  "Isle of Man"="Isl. Man",
  "Channel Islands"="Ch. Isl.",
  "Northern Ireland"="N. Ire.",
  "Wales"="Wales",
  "Scotland"="Scot.",
  "England"="Eng.",
  "North East"="N. East",
  "North West"="N. West",
  "Yorks & Humber"="Yorks.",
  "East Midlands"="East Mids",
  "West Midlands"="West Mids",
  "East of England"="East Eng",
  "London"="London",
  "South East"="S. East",
  "South West"="S. West",
  # accreditation
  "accredited"="accred.",
  "unaccredited"="unaccred.",
  # subject
  "other"="other",
  "mixed: other"="other",
  "mixed: encyclopaedic"="encyclopaedic",
  "mixed: bygones"="bygones",
  "mixed"="mixed",
  "war & conflict: other"="other",
  "war & conflict: regiment"="regiment",
  "war & conflict: navy"="navy",
  "war & conflict: military"="military",
  "war & conflict: event or site"="event/site",
  "war & conflict: castles & forts"="castles&forts",
  "war & conflict: bunker"="bunker",
  "war & conflict: airforce"="airforce",
  "war & conflict"="war&conf",
  "utilities: water & waste"="water&waste",
  "utilities: gas & electricity"="gas&electric",
  "utilities"="utilities",
  "transport: other"="other",
  "transport: mixed"="mixed",
  "transport: trains & railways"="trains&railways",
  "transport: cars & motorbikes"="cars&motorbikes",
  "transport: canals"="canals",
  "transport: buses & trams"="buses&trams",
  "transport: bicycles"="bicycles",
  "transport: aviation"="aviation",
  "transport"="transport",
  "services: other"="other",
  "services: rnli"="rnli",
  "services: police"="police",
  "services: fire"="fire",
  "services"="services",
  "sea & seafaring: other"="other",
  "sea & seafaring: mixed"="mixed",
  "sea & seafaring: lighthouses"="lighthouses",
  "sea & seafaring: fishing"="fishing",
  "sea & seafaring: boats & ships"="boats&ships",
  "sea & seafaring"="seafaring",
  "science & technology: other"="other",
  "science & technology: computing & gaming"="computing&gaming",
  "science & technology"="sci&tech",
  "rural industry: other"="other",
  "rural industry: windmills"="windmills",
  "rural industry: watermills"="watermills",
  "rural industry: textiles"="textiles",
  "rural industry: rural life"="rural life",
  "rural industry: forges"="forges",
  "rural industry: farming"="farming",
  "rural industry"="rural ind",
  "personality: other"="other",
  "personality: scientific"="scientific",
  "personality: religious"="religious",
  "personality: political"="political",
  "personality: music"="music",
  "personality: literary"="literary",
  "personality: explorer"="explorer",
  "personality: art"="art",
  "personality"="personality",
  "natural world: other"="other",
  "natural world: mixed"="mixed",
  "natural world: zoology"="zoology",
  "natural world: herbaria & gardening"="herbaria&gardening",
  "natural world: geology"="geology",
  "natural world: fossils"="fossils",
  "natural world: dinosaurs"="dinosaurs",
  "natural world"="nat world",
  "medicine & health: other"="other",
  "medicine & health: professional association"="prof. assoc.",
  "medicine & health: hospital"="hospital",
  "medicine & health"="med&health",
  "local histories"="local hist",
  "leisure & sport: other"="other",
  "leisure & sport: toys & models"="toys&models",
  "leisure & sport: rugby & football"="rugby&football",
  "leisure & sport: film cinema & tv"="film,cinema,tv",
  "leisure & sport: fairgrounds & amusements"="fairgrounds&amusements",
  "leisure & sport: cricket"="cricket",
  "leisure & sport"="leis&sport",
  "industry & manufacture: other"="other",
  "industry & manufacture: mixed"="mixed",
  "industry & manufacture: textiles"="textiles",
  "industry & manufacture: steam & engines"="steam&engines",
  "industry & manufacture: print"="print",
  "industry & manufacture: potteries"="potteries",
  "industry & manufacture: mining & quarrying"="mining&quarrying",
  "industry & manufacture: metals"="metals",
  "industry & manufacture: industrial life"="industrial life",
  "industry & manufacture: clocks & watches"="clocks&watches",
  "industry & manufacture"="industry",
  "food & drink"="food&drink",
  "communications: other"="other",
  "communications: radio"="radio",
  "communications: post"="post",
  "communications"="comms",
  "buildings: other"="other",
  "buildings: shops"="shops",
  "buildings: school"="school",
  "buildings: penal"="penal",
  "buildings: palace"="palace",
  "buildings: houses (small)"="houses (small)",
  "buildings: houses (medium)"="houses (medium)",
  "buildings: houses (large)"="houses (large)",
  "buildings: civic"="civic",
  "buildings"="buildings",
  "belief & identity: other"="other",
  "belief & identity: religious buildings"="relig. buildings",
  "belief & identity: religion"="religion",
  "belief & identity: freemasons"="freemasons",
  "belief & identity: ethnic group"="ethnic group",
  "belief & identity: church treasuries"="church treasuries",
  "belief & identity"="belief&id",
  "arts: other"="other",
  "arts: photography"="photography",
  "arts: music"="music",
  "arts: literature"="literature",
  "arts: glass"="glass",
  "arts: fine & decorative arts"="fine&decorative",
  "arts: design"="design",
  "arts: crafts"="crafts",
  "arts: costume & textiles"="costume&textiles",
  "arts: ceramics"="ceramics",
  "arts"="arts",
  "archaeology: other"="other",
  "archaeology: mixed"="mixed",
  "archaeology: roman"="roman",
  "archaeology: prehistory"="prehistory",
  "archaeology: medieval"="medieval",
  "archaeology: greek & egyptian"="greek&egyptian",
  "archaeology"="archaeology",
  # destination outcome
  "mostly no move"="mostly no move",
  "mostly within the same LAD"="mostly within the same LAD",
  "mostly within the same region"="mostly within the same region",
  "mostly within the UK"="mostly within the UK",
  "mostly abroad"="mostly abroad",
  "mixed destinations"="mixed destinations",
  # collection share
  "'few'"="'few'",
  "'some'"="'some'",
  "'half'"="'half'",
  "'most'"="'most'",
  "'all'"="'all'",
  # recipient count outcome
  "many"="many",
  "> 5"="> 5",
  "5"="5",
  "4"="4",
  "3"="3",
  "2"="2",
  "1"="1",
  "0"="0",
  # recipient outcome
  "mostly N/A"="mostly N/A",
  "mostly storage"="mostly storage",
  "mostly museum service"="mostly museum service",
  "mostly museum"="mostly museum",
  "mostly library/archive"="mostly library/archive",
  "mostly temporary museum"="mostly temporary museum",
  "mostly heritage"="mostly heritage",
  "mostly education/research"="mostly education/research",
  "mostly society"="mostly society",
  "mostly civic organisation"="mostly civic organisation",
  "mostly service"="mostly service",
  "mostly armed forces"="mostly armed forces",
  "mostly leisure"="mostly leisure",
  "mostly transport provider"="mostly transport provider",
  "mostly other organisation"="mostly other organisation",
  "mostly company"="mostly company",
  "mostly trader"="mostly trader",
  "mostly individual"="mostly individual",
  "mostly unspecified actor"="mostly unspecified actor",
  "mostly end of existence"="mostly end of existence",
  # event outcome
  "mostly kept"="mostly kept",
  "mostly left-in-situ"="mostly left-in-situ",
  "mostly rescued"="mostly rescued",
  "mostly recorded"="mostly recorded",
  "mostly modified"="mostly modified",
  "mostly used"="mostly used",
  "mostly displayed"="mostly displayed",
  "mostly stored"="mostly stored",
  "mostly loaned"="mostly loaned",
  "mostly moved"="mostly moved",
  "mostly returned"="mostly returned",
  "mostly transferred"="mostly transferred",
  "mostly sold"="mostly sold",
  "mostly lost/stolen"="mostly lost/stolen",
  "mostly damaged/destroyed"="mostly damaged/destroyed",
  "mixed"="mixed",
  "mostly unknown"="mostly unknown",
  # reason for closure
  "other"="other",
  "financial"="financial",
  "low visitor numbers"="low visitors",
  "loss of premises"="loss premises",
  "destruction"="destruction",
  "collections"="collections",
  "building"="building",
  "strategic closure"="strategic",
  "restructure of host organisation"="restructure of host",
  "dispute"="dispute",
  "life events"="life events",
  "staff"="staff"
)

very_short_labels <- c(
  "all"="all",
  # size
  "unknown"="U",
  "small"="S",
  "medium"="M",
  "large"="L",
  "huge"="H",
  # governance
  "Unknown"="Unk",
  "Private"="Prv",
  "Independent"="Ind",
  "Independent-Not for profit"="NProf",
  "Independent-National Trust for Scotland"="NTS",
  "Independent-National Trust"="NT",
  "Independent-English Heritage"="EH",
  "Independent-Historic Environment Scotland"="HES",
  "University"="Uni",
  "Other Government"="OGov",
  "Local Authority"="LocA",
  "National"="Nat",
  # country / region
  "Isle of Man"="IoM",
  "Channel Islands"="CI",
  "Northern Ireland"="NI",
  "Wales"="Wal",
  "Scotland"="Sco",
  "England"="En",
  "North East (English Region)"="NE",
  "North West (English Region)"="NW",
  "Yorkshire & The Humber (English Region)"="Y&H",
  "East Midlands (English Region)"="EM",
  "West Midlands (English Region)"="WM",
  "East of England (English Region)"="EE",
  "London (English Region)"="Lon",
  "South East (English Region)"="SE",
  "South West (English Region)"="SW",
  # accreditation
  "Accredited"="Acc",
  "Unaccredited"="Unac",
  # subject
  "other"="oth",
  "mixed: other"="other",
  "mixed: encyclopaedic"="encyc.",
  "mixed: bygones"="bygones",
  "mixed"="mxd",
  "war & conflict: other"="other",
  "war & conflict: regiment"="reg.",
  "war & conflict: navy"="navy",
  "war & conflict: military"="mil",
  "war & conflict: event or site"="event/site",
  "war & conflict: castles & forts"="castle/fort",
  "war & conflict: bunker"="bunker",
  "war & conflict: airforce"="airf.",
  "war & conflict"="w&c",
  "utilities: water & waste"="water/waste",
  "utilities: gas & electricity"="gas/elec",
  "utilities"="ut",
  "transport: other"="other",
  "transport: mixed"="mixed",
  "transport: trains & railways"="train/rail",
  "transport: cars & motorbikes"="car/moto",
  "transport: canals"="canal",
  "transport: buses & trams"="bus/tram",
  "transport: bicycles"="bicyc.",
  "transport: aviation"="aviat.",
  "transport"="trn",
  "services: other"="other",
  "services: rnli"="rnli",
  "services: police"="police",
  "services: fire"="fire",
  "services"="srv",
  "sea & seafaring: other"="other",
  "sea & seafaring: mixed"="mixed",
  "sea & seafaring: lighthouses"="lighths",
  "sea & seafaring: fishing"="fish",
  "sea & seafaring: boats & ships"="boat/ship",
  "sea & seafaring"="sea",
  "science & technology: other"="other",
  "science & technology: computing & gaming"="comput.",
  "science & technology"="s&t",
  "rural industry: other"="other",
  "rural industry: windmills"="windmill",
  "rural industry: watermills"="watermill",
  "rural industry: textiles"="textiles",
  "rural industry: rural life"="rurallife",
  "rural industry: forges"="forge",
  "rural industry: farming"="farm",
  "rural industry"="ri",
  "personality: other"="other",
  "personality: scientific"="sci.",
  "personality: religious"="relig.",
  "personality: political"="polit.",
  "personality: music"="music",
  "personality: literary"="lit.",
  "personality: explorer"="expl.",
  "personality: art"="art",
  "personality"="prs",
  "natural world: other"="other",
  "natural world: mixed"="mixed",
  "natural world: zoology"="zoology",
  "natural world: herbaria & gardening"="herb/garden",
  "natural world: geology"="geology",
  "natural world: fossils"="foss",
  "natural world: dinosaurs"="dino",
  "natural world"="nw",
  "medicine & health: other"="other",
  "medicine & health: professional association"="prof.assoc.",
  "medicine & health: hospital"="hospital",
  "medicine & health"="m&h",
  "local histories"="lh",
  "leisure & sport: other"="other",
  "leisure & sport: toys & models"="toys/models",
  "leisure & sport: rugby & football"="rugby&foot",
  "leisure & sport: film cinema & tv"="film/cin/tv",
  "leisure & sport: fairgrounds & amusements"="fair/amusem",
  "leisure & sport: cricket"="cricket",
  "leisure & sport"="l&s",
  "industry & manufacture: other"="other",
  "industry & manufacture: mixed"="mixed",
  "industry & manufacture: textiles"="textiles",
  "industry & manufacture: steam & engines"="steam/eng",
  "industry & manufacture: print"="print",
  "industry & manufacture: potteries"="pottery",
  "industry & manufacture: mining & quarrying"="mine/quarry",
  "industry & manufacture: metals"="metals",
  "industry & manufacture: industrial life"="indust.life",
  "industry & manufacture: clocks & watches"="clock/watch",
  "industry & manufacture"="i&m",
  "food & drink"="f&d",
  "communications: other"="other",
  "communications: radio"="radio",
  "communications: post"="post",
  "communications"="com",
  "buildings: other"="other",
  "buildings: shops"="shops",
  "buildings: school"="school",
  "buildings: penal"="penal",
  "buildings: palace"="palace",
  "buildings: houses: small houses"="house(s)",
  "buildings: houses: medium houses"="house(m)",
  "buildings: houses: large houses"="house(l)",
  "buildings: civic"="civic",
  "buildings"="bld",
  "belief & identity: other"="other",
  "belief & identity: religious buildings"="rel.blds",
  "belief & identity: religion"="religion",
  "belief & identity: freemasons"="freemas.",
  "belief & identity: ethnic group"="ethnic",
  "belief & identity: church treasuries"="ch.treas.",
  "belief & identity"="b&i",
  "arts: other"="other",
  "arts: photography"="photo.",
  "arts: music"="music",
  "arts: literature"="lit.",
  "arts: glass"="glass",
  "arts: fine & decorative arts"="fine/decor.",
  "arts: design"="design",
  "arts: crafts"="crafts",
  "arts: costume & textiles"="cost./textil",
  "arts: ceramics"="ceram.",
  "arts"="art",
  "archaeology: other"="other",
  "archaeology: mixed"="mixed",
  "archaeology: roman"="roman",
  "archaeology: prehistory"="prehist.",
  "archaeology: medieval"="mediev.",
  "archaeology: greek & egyptian"="gr./egpt",
  "archaeology"="arc",
  # destination outcome
  "mostly no move"="mostly no move",
  "mostly within the same LAD"="mostly within the same LAD",
  "mostly within the same region"="mostly within the same region",
  "mostly within the UK"="mostly within the UK",
  "mostly abroad"="mostly abroad",
  "mixed destinations"="mixed destinations",
  # collection share
  "'few'"="'few'",
  "'some'"="'some'",
  "'half'"="'half'",
  "'most'"="'most'",
  "'all'"="'all'",
  # recipient count outcome
  "many"="many",
  "> 5"="> 5",
  "5"="5",
  "4"="4",
  "3"="3",
  "2"="2",
  "1"="1",
  "0"="0",
  # recipient outcome
  "mostly N/A"="mostly N/A",
  "mostly storage"="mostly storage",
  "mostly museum service"="mostly museum service",
  "mostly museum"="mostly museum",
  "mostly library/archive"="mostly library/archive",
  "mostly temporary museum"="mostly temporary museum",
  "mostly heritage"="mostly heritage",
  "mostly education/research"="mostly education/research",
  "mostly society"="mostly society",
  "mostly civic organisation"="mostly civic organisation",
  "mostly service"="mostly service",
  "mostly armed forces"="mostly armed forces",
  "mostly leisure"="mostly leisure",
  "mostly transport provider"="mostly transport provider",
  "mostly other organisation"="mostly other organisation",
  "mostly company"="mostly company",
  "mostly trader"="mostly trader",
  "mostly individual"="mostly individual",
  "mostly unspecified actor"="mostly unspecified actor",
  "mostly end of existence"="mostly end of existence",
  # event outcome
  "mostly kept"="mostly kept",
  "mostly left-in-situ"="mostly left-in-situ",
  "mostly rescued"="mostly rescued",
  "mostly recorded"="mostly recorded",
  "mostly modified"="mostly modified",
  "mostly used"="mostly used",
  "mostly displayed"="mostly displayed",
  "mostly stored"="mostly stored",
  "mostly loaned"="mostly loaned",
  "mostly moved"="mostly moved",
  "mostly returned"="mostly returned",
  "mostly transferred"="mostly transferred",
  "mostly sold"="mostly sold",
  "mostly lost/stolen"="mostly lost/stolen",
  "mostly damaged/destroyed"="mostly damaged/destroyed",
  "mixed"="mixed",
  "mostly unknown"="mostly unknown",
  # reason for closure
  "other"="other",
  "financial"="financial",
  "low visitor numbers"="low visitors",
  "loss of premises"="loss premises",
  "destruction"="destruction",
  "collections"="collections",
  "building"="building",
  "strategic closure"="strategic",
  "restructure of host organisation"="restructure of host",
  "dispute"="dispute",
  "life events"="life events",
  "staff"="staff"
)

museum_attribute_ordering <- c(
  "all",
  # size
  "unknown size",
  "small",
  "medium",
  "large",
  "huge",
  # governance
  "unknown governance",
  "private",
  "independent",
  "Historic Environment Scotland",
  "National Trust for Scotland",
  "National Trust",
  "English Heritage",
  "not-for-profit",
  "university",
  "other government",
  "local authority",
  "national",
  # region/country
  "Isle of Man",
  "Channel Islands",
  "Northern Ireland",
  "Wales",
  "Scotland",
  "England",
  "North East",
  "North West",
  "Yorks & Humber",
  "East Midlands",
  "West Midlands",
  "East of England",
  "London",
  "South East",
  "South West",
  # accreditation
  "unaccredited",
  "accredited",
  # subject
  "other",
  "mixed: other",
  "mixed: encyclopaedic",
  "mixed: bygones",
  "mixed",
  "war & conflict: other",
  "war & conflict: regiment",
  "war & conflict: navy",
  "war & conflict: military",
  "war & conflict: event or site",
  "war & conflict: castles & forts",
  "war & conflict: bunker",
  "war & conflict: airforce",
  "war & conflict",
  "utilities: water & waste",
  "utilities: gas & electricity",
  "utilities",
  "transport: other",
  "transport: mixed",
  "transport: trains & railways",
  "transport: cars & motorbikes",
  "transport: canals",
  "transport: buses & trams",
  "transport: bicycles",
  "transport: aviation",
  "transport",
  "services: other",
  "services: rnli",
  "services: police",
  "services: fire",
  "services",
  "sea & seafaring: other",
  "sea & seafaring: mixed",
  "sea & seafaring: lighthouses",
  "sea & seafaring: fishing",
  "sea & seafaring: boats & ships",
  "sea & seafaring",
  "science & technology: other",
  "science & technology: computing & gaming",
  "science & technology",
  "rural industry: other",
  "rural industry: windmills",
  "rural industry: watermills",
  "rural industry: textiles",
  "rural industry: rural life",
  "rural industry: forges",
  "rural industry: farming",
  "rural industry",
  "personality: other",
  "personality: scientific",
  "personality: religious",
  "personality: political",
  "personality: music",
  "personality: literary",
  "personality: explorer",
  "personality: art",
  "personality",
  "natural world: other",
  "natural world: mixed",
  "natural world: zoology",
  "natural world: herbaria & gardening",
  "natural world: geology",
  "natural world: fossils",
  "natural world: dinosaurs",
  "natural world",
  "medicine & health: other",
  "medicine & health: professional association",
  "medicine & health: hospital",
  "medicine & health",
  "local histories",
  "leisure & sport: other",
  "leisure & sport: toys & models",
  "leisure & sport: rugby & football",
  "leisure & sport: film cinema & tv",
  "leisure & sport: fairgrounds & amusements",
  "leisure & sport: cricket",
  "leisure & sport",
  "industry & manufacture: other",
  "industry & manufacture: mixed",
  "industry & manufacture: textiles",
  "industry & manufacture: steam & engines",
  "industry & manufacture: print",
  "industry & manufacture: potteries",
  "industry & manufacture: mining & quarrying",
  "industry & manufacture: metals",
  "industry & manufacture: industrial life",
  "industry & manufacture: clocks & watches",
  "industry & manufacture",
  "food & drink",
  "communications: other",
  "communications: radio",
  "communications: post",
  "communications",
  "buildings: other",
  "buildings: shops",
  "buildings: school",
  "buildings: penal",
  "buildings: palace",
  "buildings: houses (small)",
  "buildings: houses (medium)",
  "buildings: houses (large)",
  "buildings: civic",
  "buildings",
  "belief & identity: other",
  "belief & identity: religious buildings",
  "belief & identity: religion",
  "belief & identity: freemasons",
  "belief & identity: ethnic group",
  "belief & identity: church treasuries",
  "belief & identity",
  "arts: other",
  "arts: photography",
  "arts: music",
  "arts: literature",
  "arts: glass",
  "arts: fine & decorative arts",
  "arts: design",
  "arts: crafts",
  "arts: costume & textiles",
  "arts: ceramics",
  "arts",
  "archaeology: other",
  "archaeology: mixed",
  "archaeology: roman",
  "archaeology: prehistory",
  "archaeology: medieval",
  "archaeology: greek & egyptian",
  "archaeology",
  # destination outcome
  "mostly no move",
  "mostly within the same LAD",
  "mostly within the same region",
  "mostly within the UK",
  "mostly abroad",
  "mixed destinations",
  # collection share
  "'few'",
  "'some'",
  "'half'",
  "'most'",
  "'all'",
  # recipient count outcome
  "many",
  "> 5",
  "5",
  "4",
  "3",
  "2",
  "1",
  "0",
  # recipient outcome
  "mostly N/A",
  "mostly storage",
  "mostly museum service",
  "mostly museum",
  "mostly library/archive",
  "mostly temporary museum",
  "mostly heritage",
  "mostly education/research",
  "mostly society",
  "mostly civic organisation",
  "mostly service",
  "mostly armed forces",
  "mostly leisure",
  "mostly transport provider",
  "mostly other organisation",
  "mostly company",
  "mostly trader",
  "mostly individual",
  "mostly unspecified actor",
  "mostly end of existence",
  # event outcome
  "mostly kept",
  "mostly left-in-situ",
  "mostly rescued",
  "mostly recorded",
  "mostly modified",
  "mostly used",
  "mostly displayed",
  "mostly stored",
  "mostly loaned",
  "mostly moved",
  "mostly returned",
  "mostly transferred",
  "mostly sold",
  "mostly lost/stolen",
  "mostly damaged/destroyed",
  "mostly unknown",
  # reason for closure
  "financial",
  "low visitor numbers",
  "loss of premises",
  "destruction",
  "collections",
  "building",
  "strategic closure",
  "restructure of host organisation",
  "dispute",
  "life events",
  "staff"
)
