tidy_labels_size <- c(
  "unknown"="Unknown",
  "small"="Small",
  "medium"="Medium",
  "large"="Large",
  "huge"="Huge"
)
size_labels <- data.frame(
  internal_label=c("unknown", "small", "medium", "large", "huge"),
  tidy_label=c("Unknown", "Small", "Medium", "Large", "Huge"),
  default_filter=c(TRUE, TRUE, TRUE, TRUE, TRUE)
)

tidy_labels_governance <- c(
  "Unknown"="Unknown",
  "Private"="Private",
  "Independent"="Independent",
  "Independent-Not_for_profit"="Not for Profit",
  "Independent-National_Trust_for_Scotland"="National Trust Scot.",
  "Independent-National_Trust"="National Trust",
  "Independent-English_Heritage"="English Heritage",
  "Independent-Historic_Environment_Scotland"="Historic Environment Scot.",
  "University"="University",
  "National"="National",
  "Local_Authority"="Local Authority",
  "Other_Government"="Other Government"
)
governance_labels <- data.frame(
  internal_label=c(
    "Unknown",
    "Private",
    "Independent",
    "Independent-Not_for_profit",
    "Independent-National_Trust_for_Scotland",
    "Independent-National_Trust",
    "Independent-English_Heritage",
    "Independent-Historic_Environment_Scotland",
    "University",
    "National",
    "Local_Authority",
    "Other_Government"
  ),
  tidy_label=c(
    "Unknown",
    "Private",
    "Independent",
    "Not for Profit",
    "National Trust Scot.",
    "National Trust",
    "English Heritage",
    "Historic Environment Scot.",
    "University",
    "National",
    "Local Authority",
    "Other Government"
  ),
  default_filter=c(
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE
  )
)
    

governance_choices <- setNames(names(tidy_labels_governance), tidy_labels_governance)
governance_to_sector <- c(
  "Unknown"="unknown",
  "Private"="private",
  "Independent"="third",
  "Independent-Not_for_profit"="third",
  "Independent-National_Trust_for_Scotland"="third",
  "Independent-National_Trust"="third",
  "Independent-English_Heritage"="third",
  "Independent-Historic_Environment_Scotland"="third",
  "University"="university",
  "National"="public",
  "Local_Authority"="public",
  "Other_Government"="public"
)

tidy_labels_country_region <- c(
    "Isle of Man"="Isle of Man",
    "Channel Islands"="Channel Islands",
    "Northern Ireland"="Northern Ireland",
    "Wales"="Wales",
    "Scotland"="Scotland",
    "England"="England",
    "North East (English Region)"="North East",
    "North West (English Region)"="North West",
    "Yorkshire and The Humber (English Region)"="Yorks & Humber",
    "East Midlands (English Region)"="East Midlands",
    "West Midlands (English Region)"="West Midlands",
    "South East (English Region)"="South East",
    "South West (English Region)"="South West",
    "East of England (English Region)"="East of England",
    "London (English Region)"="London"
)
country_region_labels <- data.frame(
  internal_label=c(
    "Isle of Man",
    "Channel Islands",
    "Northern Ireland",
    "Wales",
    "Scotland",
    "England",
    "North East (English Region)",
    "North West (English Region)",
    "Yorkshire and The Humber (English Region)",
    "East Midlands (English Region)",
    "West Midlands (English Region)",
    "South East (English Region)",
    "South West (English Region)",
    "East of England (English Region)",
    "London (English Region)"
  ),
  tidy_label=c(
    "Isle of Man",
    "Channel Islands",
    "Northern Ireland",
    "Wales",
    "Scotland",
    "England",
    "North East",
    "North West",
    "Yorks & Humber",
    "East Midlands",
    "West Midlands",
    "South East",
    "South West",
    "East of England",
    "London"
  ),
  default_filter=c(
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE
  )
)

tidy_labels_accreditation <- c(
    "Accredited"="Accredited",
    "Unaccredited"="Unaccredited"
)
accreditation_labels <- data.frame(
  internal_label=c("Accredited", "Unaccredited"),
  tidy_label=c("Accredited", "Unaccredited"),
  default_filter=c(TRUE, TRUE)
)

tidy_labels_subject <- c(
  "War_and_conflict"="War & Conflict",
  "Utilities"="Utilities",
  "Transport"="Transport",
  "Services"="Services",
  "Sea_and_seafaring"="Sea & Seafaring",
  "Science_and_technology"="Science & Technology",
  "Rural_Industry"="Rural Industry",
  "Personality"="Personality",
  "Other"="Other",
  "Natural_world"="Natural World",
  "Mixed"="Mixed",
  "Medicine_and_health"="Medicine & Health",
  "Local_Histories"="Local Histories",
  "Leisure_and_sport"="Leisure & Sport",
  "Industry_and_manufacture"="Industry & Manufacture",
  "Food_and_drink"="Food & Drink",
  "Communications"="Communications",
  "Buildings"="Buildings",
  "Belief_and_identity"="Belief & Identity",
  "Arts"="Arts",
  "Archaeology"="Archaeology"
)
subject_broad_labels <- data.frame(
  internal_label=c(
    "War_and_conflict",
    "Utilities",
    "Transport",
    "Services",
    "Sea_and_seafaring",
    "Science_and_technology",
    "Rural_Industry",
    "Personality",
    "Other",
    "Natural_world",
    "Mixed",
    "Medicine_and_health",
    "Local_Histories",
    "Leisure_and_sport",
    "Industry_and_manufacture",
    "Food_and_drink",
    "Communications",
    "Buildings",
    "Belief_and_identity",
    "Arts",
    "Archaeology"
  ),
  tidy_label=c(
    "War & Conflict",
    "Utilities",
    "Transport",
    "Services",
    "Sea & Seafaring",
    "Science & Technology",
    "Rural Industry",
    "Personality",
    "Other",
    "Natural World",
    "Mixed",
    "Medicine & Health",
    "Local Histories",
    "Leisure & Sport",
    "Industry & Manufacture",
    "Food & Drink",
    "Communications",
    "Buildings",
    "Belief & Identity",
    "Arts",
    "Archaeology"
  ),
  default_filter=c(
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE
  )
)

tidy_labels_subject_full <- c(
  "Archaeology-Greek_and_Egyptian"="Archaeology: Greek & Egyptian",
  "Archaeology-Medieval"="Archaeology: Medieval",
  "Archaeology-Prehistory"="Archaeology: Prehistory",
  "Archaeology-Roman"="Archaeology: Roman",
  "Archaeology-Mixed"="Archaeology: Mixed",
  "Archaeology-Other"="Archaeology: Other",
  "Arts-Ceramics"="Arts: Ceramics",
  "Arts-Costume_and_textiles"="Arts: Costume & Textiles",
  "Arts-Crafts"="Arts: Crafts",
  "Arts-Design"="Arts: Design",
  "Arts-Fine_and_decorative_arts"="Arts: Fine & Decorative Arts",
  "Arts-Glass"="Arts: Glass",
  "Arts-Literature"="Arts: Literature",
  "Arts-Music"="Arts: Music",
  "Arts-Photography"="Arts: Photography",
  "Arts-Other"="Arts: Other",
  "Belief_and_identity-Church_treasuries"="Belief & Identity: Church Treasuries",
  "Belief_and_identity-Ethnic_group"="Belief & Identity: Ethnic Group",
  "Belief_and_identity-Freemasons"="Belief & Identity: Freemasons",
  "Belief_and_identity-Religion"="Belief & Identity: Religion",
  "Belief_and_identity-Religious_buildings"="Belief & Identity: Religious Buildings",
  "Belief_and_identity-Other"="Belief & Identity: Other",
  "Buildings-Civic"="Buildings: Civic",
  "Buildings-Houses-Large_houses"="Buildings: Houses (Large)",
  "Buildings-Houses-Medium_houses"="Buildings: Houses (Medium)",
  "Buildings-Houses-Small_houses"="Buildings: Houses (Small)",
  "Buildings-Palace"="Buildings: Palace",
  "Buildings-Penal"="Buildings: Penal",
  "Buildings-School"="Buildings: School",
  "Buildings-Shops"="Buildings: Shops",
  "Buildings-Other"="Buildings: Other",
  "Communications-Post"="Communications: Post",
  "Communications-Radio"="Communications: Radio",
  "Communications-Other"="Communications: Other",
  "Industry_and_manufacture-Clocks_and_watches"="Industry & Manufacture: Clocks & Watches",
  "Industry_and_manufacture-Industrial_life"="Industry & Manufacture: Industrial Life",
  "Industry_and_manufacture-Metals"="Industry & Manufacture: Metals",
  "Industry_and_manufacture-Mining_and_quarrying"="Industry & Manufacture: Mining & Quarrying",
  "Industry_and_manufacture-Potteries"="Industry & Manufacture: Potteries",
  "Industry_and_manufacture-Print"="Industry & Manufacture: Print",
  "Industry_and_manufacture-Steam_and_engines"="Industry & Manufacture: Steam & Engines",
  "Industry_and_manufacture-Textiles"="Industry & Manufacture: Textiles",
  "Industry_and_manufacture-Mixed"="Industry & Manufacture: Mixed",
  "Industry_and_manufacture-Other"="Industry & Manufacture: Other",
  "Leisure_and_sport-Cricket"="Leisure & Sport: Cricket",
  "Leisure_and_sport-Fairgrounds_and_amusements"="Leisure & Sport: Fairgrounds & Amusements",
  "Leisure_and_sport-Film_Cinema_and_TV"="Leisure & Sport: Film, Cinema & TV",
  "Leisure_and_sport-Rugby_and_football"="Leisure & Sport: Rugby & Football",
  "Leisure_and_sport-Toys_and_models"="Leisure & Sport: Toys & Models",
  "Leisure_and_sport-Other"="Leisure & Sport: Other",
  "Medicine_and_health-Hospital"="Medicine & Health: Hospital",
  "Medicine_and_health-Professional_association"="Medicine & Health: Professional Association",
  "Medicine_and_health-Other"="Medicine & Health: Other",
  "Natural_world-Dinosaurs"="Natural World: Dinosaurs",
  "Natural_world-Fossils"="Natural World: Fossils",
  "Natural_world-Geology"="Natural World: Geology",
  "Natural_world-Herbaria_and_gardening"="Natural World: Herbaria & Gardening",
  "Natural_world-Zoology"="Natural World: Zoology",
  "Natural_world-Mixed"="Natural World: Mixed",
  "Natural_world-Other"="Natural World: Other",
  "Personality-Art"="Personality: Art",
  "Personality-Explorer"="Personality: Explorer",
  "Personality-Literary"="Personality: Literary",
  "Personality-Music"="Personality: Music",
  "Personality-Political"="Personality: Political",
  "Personality-Religious"="Personality: Religious",
  "Personality-Scientific"="Personality: Scientific",
  "Personality-Other"="Personality: Other",
  "Rural_Industry-Farming"="Rural Industry: Farming",
  "Rural_Industry-Forges"="Rural Industry: Forges",
  "Rural_Industry-Rural_life"="Rural Industry: Rural Life",
  "Rural_Industry-Textiles"="Rural Industry: Textiles",
  "Rural_Industry-Watermills"="Rural Industry: Watermills",
  "Rural_Industry-Windmills"="Rural Industry: Windmills",
  "Rural_Industry-Other"="Rural Industry: Other",
  "Science_and_technology-Computing_and_gaming"="Science & Technology: Computing & Gaming",
  "Science_and_technology-Other"="Science & Technology: Other",
  "Sea_and_seafaring-Boats_and_ships"="Sea & Seafaring: Boats & Ships",
  "Sea_and_seafaring-Fishing"="Sea & Seafaring: Fishing",
  "Sea_and_seafaring-Lighthouses"="Sea & Seafaring: Lighthouses",
  "Sea_and_seafaring-Mixed"="Sea & Seafaring: Mixed",
  "Sea_and_seafaring-Other"="Sea & Seafaring: Other",
  "Services-Fire"="Services: Fire",
  "Services-Police"="Services: Police",
  "Services-RNLI"="Services: RNLI",
  "Services-Other"="Services: Other",
  "Transport-Aviation"="Transport: Aviation",
  "Transport-Bicycles"="Transport: Bicycles",
  "Transport-Buses_and_trams"="Transport: Buses & Trams",
  "Transport-Canals"="Transport: Canals",
  "Transport-Cars_and_motorbikes"="Transport: Cars & Motorbikes",
  "Transport-Trains_and_railways"="Transport: Trains & Railways",
  "Transport-Mixed"="Transport: Mixed",
  "Transport-Other"="Transport: Other",
  "Utilities-Gas_and_electricity"="Utilities: Gas & Electricity",
  "Utilities-Water_and_waste"="Utilities: Water & Waste",
  "War_and_conflict-Airforce"="War & Conflict: Airforce",
  "War_and_conflict-Bunker"="War & Conflict: Bunker",
  "War_and_conflict-Castles_and_forts"="War & Conflict: Castles & Forts",
  "War_and_conflict-Event_or_site"="War & Conflict: Event or Site",
  "War_and_conflict-Military"="War & Conflict: Military",
  "War_and_conflict-Navy"="War & Conflict: Navy",
  "War_and_conflict-Regiment"="War & Conflict: Regiment",
  "War_and_conflict-Other"="War & Conflict: Other",
  "Mixed-Bygones"="Mixed: Bygones",
  "Mixed-Encyclopaedic"="Mixed: Encyclopaedic",
  "Mixed-Other"="Mixed: Other"
)

subject_full_labels <- data.frame(
  internal_label=c(
    "Archaeology-Greek_and_Egyptian",
    "Archaeology-Medieval",
    "Archaeology-Prehistory",
    "Archaeology-Roman",
    "Archaeology-Mixed",
    "Archaeology-Other",
    "Archaeology",
    "Arts-Ceramics",
    "Arts-Costume_and_textiles",
    "Arts-Crafts",
    "Arts-Design",
    "Arts-Fine_and_decorative_arts",
    "Arts-Glass",
    "Arts-Literature",
    "Arts-Music",
    "Arts-Photography",
    "Arts-Other",
    "Belief_and_identity-Church_treasuries",
    "Belief_and_identity-Ethnic_group",
    "Belief_and_identity-Freemasons",
    "Belief_and_identity-Religion",
    "Belief_and_identity-Religious_buildings",
    "Belief_and_identity-Other",
    "Belief_and_identity",
    "Buildings-Civic",
    "Buildings-Houses-Large_houses",
    "Buildings-Houses-Medium_houses",
    "Buildings-Houses-Small_houses",
    "Buildings-Palace",
    "Buildings-Penal",
    "Buildings-School",
    "Buildings-Shops",
    "Buildings-Other",
    "Communications-Post",
    "Communications-Radio",
    "Communications-Other",
    "Communications",
    "Food_and_drink",
    "Industry_and_manufacture-Clocks_and_watches",
    "Industry_and_manufacture-Industrial_life",
    "Industry_and_manufacture-Metals",
    "Industry_and_manufacture-Mining_and_quarrying",
    "Industry_and_manufacture-Potteries",
    "Industry_and_manufacture-Print",
    "Industry_and_manufacture-Steam_and_engines",
    "Industry_and_manufacture-Textiles",
    "Industry_and_manufacture-Mixed",
    "Industry_and_manufacture-Other",
    "Leisure_and_sport-Cricket",
    "Leisure_and_sport-Fairgrounds_and_amusements",
    "Leisure_and_sport-Film_Cinema_and_TV",
    "Leisure_and_sport-Rugby_and_football",
    "Leisure_and_sport-Toys_and_models",
    "Leisure_and_sport-Other",
    "Local_Histories",
    "Medicine_and_health-Hospital",
    "Medicine_and_health-Professional_association",
    "Medicine_and_health-Other",
    "Natural_world-Dinosaurs",
    "Natural_world-Fossils",
    "Natural_world-Geology",
    "Natural_world-Herbaria_and_gardening",
    "Natural_world-Zoology",
    "Natural_world-Mixed",
    "Natural_world-Other",
    "Natural_world",
    "Personality-Art",
    "Personality-Explorer",
    "Personality-Literary",
    "Personality-Music",
    "Personality-Political",
    "Personality-Religious",
    "Personality-Scientific",
    "Personality-Other",
    "Rural_Industry-Farming",
    "Rural_Industry-Forges",
    "Rural_Industry-Rural_life",
    "Rural_Industry-Textiles",
    "Rural_Industry-Watermills",
    "Rural_Industry-Windmills",
    "Rural_Industry-Other",
    "Science_and_technology-Computing_and_gaming",
    "Science_and_technology-Other",
    "Sea_and_seafaring-Boats_and_ships",
    "Sea_and_seafaring-Fishing",
    "Sea_and_seafaring-Lighthouses",
    "Sea_and_seafaring-Mixed",
    "Sea_and_seafaring-Other",
    "Services-Fire",
    "Services-Police",
    "Services-RNLI",
    "Services-Other",
    "Transport-Aviation",
    "Transport-Bicycles",
    "Transport-Buses_and_trams",
    "Transport-Canals",
    "Transport-Cars_and_motorbikes",
    "Transport-Trains_and_railways",
    "Transport-Mixed",
    "Transport-Other",
    "Utilities-Gas_and_electricity",
    "Utilities-Water_and_waste",
    "War_and_conflict-Airforce",
    "War_and_conflict-Bunker",
    "War_and_conflict-Castles_and_forts",
    "War_and_conflict-Event_or_site",
    "War_and_conflict-Military",
    "War_and_conflict-Navy",
    "War_and_conflict-Regiment",
    "War_and_conflict-Other",
    "Mixed-Bygones",
    "Mixed-Encyclopaedic",
    "Mixed-Other",
    "Mixed",
    "Other"
  ),
  tidy_label=c(
    "Archaeology: Greek & Egyptian",
    "Archaeology: Medieval",
    "Archaeology: Prehistory",
    "Archaeology: Roman",
    "Archaeology: Mixed",
    "Archaeology: Other",
    "Archaeology",
    "Arts: Ceramics",
    "Arts: Costume & Textiles",
    "Arts: Crafts",
    "Arts: Design",
    "Arts: Fine & Decorative Arts",
    "Arts: Glass",
    "Arts: Literature",
    "Arts: Music",
    "Arts: Photography",
    "Arts: Other",
    "Belief & Identity: Church Treasuries",
    "Belief & Identity: Ethnic Group",
    "Belief & Identity: Freemasons",
    "Belief & Identity: Religion",
    "Belief & Identity: Religious Buildings",
    "Belief & Identity: Other",
    "Belief_and_identity",
    "Buildings: Civic",
    "Buildings: Houses (Large)",
    "Buildings: Houses (Medium)",
    "Buildings: Houses (Small)",
    "Buildings: Palace",
    "Buildings: Penal",
    "Buildings: School",
    "Buildings: Shops",
    "Buildings: Other",
    "Communications: Post",
    "Communications: Radio",
    "Communications: Other",
    "Communications",
    "Food & Drink",
    "Industry & Manufacture: Clocks & Watches",
    "Industry & Manufacture: Industrial Life",
    "Industry & Manufacture: Metals",
    "Industry & Manufacture: Mining & Quarrying",
    "Industry & Manufacture: Potteries",
    "Industry & Manufacture: Print",
    "Industry & Manufacture: Steam & Engines",
    "Industry & Manufacture: Textiles",
    "Industry & Manufacture: Mixed",
    "Industry & Manufacture: Other",
    "Leisure & Sport: Cricket",
    "Leisure & Sport: Fairgrounds & Amusements",
    "Leisure & Sport: Film, Cinema & TV",
    "Leisure & Sport: Rugby & Football",
    "Leisure & Sport: Toys & Models",
    "Leisure & Sport: Other",
    "Local Histories",
    "Medicine & Health: Hospital",
    "Medicine & Health: Professional Association",
    "Medicine & Health: Other",
    "Natural World: Dinosaurs",
    "Natural World: Fossils",
    "Natural World: Geology",
    "Natural World: Herbaria & Gardening",
    "Natural World: Zoology",
    "Natural World: Mixed",
    "Natural World: Other",
    "Natural_world",
    "Personality: Art",
    "Personality: Explorer",
    "Personality: Literary",
    "Personality: Music",
    "Personality: Political",
    "Personality: Religious",
    "Personality: Scientific",
    "Personality: Other",
    "Rural Industry: Farming",
    "Rural Industry: Forges",
    "Rural Industry: Rural Life",
    "Rural Industry: Textiles",
    "Rural Industry: Watermills",
    "Rural Industry: Windmills",
    "Rural Industry: Other",
    "Science & Technology: Computing & Gaming",
    "Science & Technology: Other",
    "Sea & Seafaring: Boats & Ships",
    "Sea & Seafaring: Fishing",
    "Sea & Seafaring: Lighthouses",
    "Sea & Seafaring: Mixed",
    "Sea & Seafaring: Other",
    "Services: Fire",
    "Services: Police",
    "Services: RNLI",
    "Services: Other",
    "Transport: Aviation",
    "Transport: Bicycles",
    "Transport: Buses & Trams",
    "Transport: Canals",
    "Transport: Cars & Motorbikes",
    "Transport: Trains & Railways",
    "Transport: Mixed",
    "Transport: Other",
    "Utilities: Gas & Electricity",
    "Utilities: Water & Waste",
    "War & Conflict: Airforce",
    "War & Conflict: Bunker",
    "War & Conflict: Castles & Forts",
    "War & Conflict: Event or Site",
    "War & Conflict: Military",
    "War & Conflict: Navy",
    "War & Conflict: Regiment",
    "War & Conflict: Other",
    "Mixed: Bygones",
    "Mixed: Encyclopaedic",
    "Mixed: Other",
    "Mixed",
    "Other"
  ),
  subject_broad=c(
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Archaeology",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Arts",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Belief_and_identity",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Buildings",
    "Communications",
    "Communications",
    "Communications",
    "Communications",
    "Food_and_drink",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Industry_and_manufacture",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Leisure_and_sport",
    "Local_Histories",
    "Medicine_and_health",
    "Medicine_and_health",
    "Medicine_and_health",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Natural_world",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Personality",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Rural_Industry",
    "Science_and_technology",
    "Science_and_technology",
    "Sea_and_seafaring",
    "Sea_and_seafaring",
    "Sea_and_seafaring",
    "Sea_and_seafaring",
    "Sea_and_seafaring",
    "Services",
    "Services",
    "Services",
    "Services",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Transport",
    "Utilities",
    "Utilities",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "War_and_conflict",
    "Mixed",
    "Mixed",
    "Mixed",
    "Mixed",
    "Other"
  )
) |>
  mutate(
    default_filter=TRUE
  )

tidy_labels <- c(
  "All"="All",
  tidy_labels_size,
  tidy_labels_governance,
  tidy_labels_country_region,
  tidy_labels_accreditation,
  tidy_labels_subject,
  tidy_labels_subject_full
)

hierarchical_filter_choices <- list(
  "Size" = unname(tidy_labels_size),
  "Governance" = unname(tidy_labels_governance),
  "Accreditation" = unname(tidy_labels_accreditation),
  "Subject" = unname(tidy_labels_subject),
  "Regions" = unname(tidy_labels_country_region)
)

short_labels <- c(
  "All"="All",
  # size
  "unknown"="Unk.",
  "small"="Small",
  "medium"="Med.",
  "large"="Large",
  "huge"="Huge",
  # governance
  "Unknown"="Unknown",
  "Private"="Private",
  "Independent"="Independent",
  "Independent-Not_for_profit"="Non-Profit",
  "Independent-National_Trust_for_Scotland"="Nat Trust S",
  "Independent-National_Trust"="Nat Trust",
  "Independent-English_Heritage"="Eng Heritage",
  "Independent-Historic_Environment_Scotland"="Hist Env S",
  "University"="University",
  "National"="National",
  "Local_Authority"="Local Auth",
  "Other_Government"="Other Gov",
  # country / region
  "Isle of Man"="Isl. Man",
  "Channel Islands"="Ch. Isl.",
  "Northern Ireland"="N. Ire.",
  "Wales"="Wales",
  "Scotland"="Scot.",
  "England"="Eng.",
  "North East (English Region)"="N. East",
  "North West (English Region)"="N. West",
  "Yorkshire and The Humber (English Region)"="Yorks.",
  "East Midlands (English Region)"="East Mids",
  "West Midlands (English Region)"="West Mids",
  "South East (English Region)"="S. East",
  "South West (English Region)"="S. West",
  "East of England (English Region)"="East Eng",
  "London (English Region)"="London",
  # accreditation
  "Accredited"="Accred.",
  "Unaccredited"="Unaccred.",
  # subject matter broad
  "War_and_conflict"="War&Conf",
  "Utilities"="Utilities",
  "Transport"="Transport",
  "Services"="Services",
  "Sea_and_seafaring"="Seafaring",
  "Science_and_technology"="Sci&Tech",
  "Rural_Industry"="Rural Ind",
  "Personality"="Personality",
  "Other"="Other",
  "Natural_world"="Nat World",
  "Mixed"="Mixed",
  "Medicine_and_health"="Med&Health",
  "Local_Histories"="Local Hist",
  "Leisure_and_sport"="Leis&Sport",
  "Industry_and_manufacture"="Industry",
  "Food_and_drink"="Food&Drink",
  "Communications"="Comms",
  "Buildings"="Buildings",
  "Belief_and_identity"="Belief&Id",
  "Arts"="Arts",
  "Archaeology"="Archaeology",
  # subject matter full
  "Archaeology-Greek_and_Egyptian"="Greek&Egyptian",
  "Archaeology-Medieval"="Medieval",
  "Archaeology-Prehistory"="Prehistory",
  "Archaeology-Roman"="Roman",
  "Archaeology-Mixed"="Mixed",
  "Archaeology-Other"="Other",
  "Arts-Ceramics"="Ceramics",
  "Arts-Costume_and_textiles"="Costume&Textiles",
  "Arts-Crafts"="Crafts",
  "Arts-Design"="Design",
  "Arts-Fine_and_decorative_arts"="Fine&Decorative",
  "Arts-Glass"="Glass",
  "Arts-Literature"="Literature",
  "Arts-Music"="Music",
  "Arts-Photography"="Photography",
  "Arts-Other"="Other",
  "Belief_and_identity-Church_treasuries"="Church Treasuries",
  "Belief_and_identity-Ethnic_group"="Ethnic Group",
  "Belief_and_identity-Freemasons"="Freemasons",
  "Belief_and_identity-Religion"="Religion",
  "Belief_and_identity-Religious_buildings"="Relig. Buildings",
  "Belief_and_identity-Other"="Other",
  "Buildings-Civic"="Civic",
  "Buildings-Houses-Large_houses"="Houses (Large)",
  "Buildings-Houses-Medium_houses"="Houses (Medium)",
  "Buildings-Houses-Small_houses"="Houses (Small)",
  "Buildings-Palace"="Palace",
  "Buildings-Penal"="Penal",
  "Buildings-School"="School",
  "Buildings-Shops"="Shops",
  "Buildings-Other"="Other",
  "Communications-Post"="Post",
  "Communications-Radio"="Radio",
  "Communications-Other"="Other",
  "Industry_and_manufacture-Clocks_and_watches"="Clocks&Watches",
  "Industry_and_manufacture-Industrial_life"="Industrial Life",
  "Industry_and_manufacture-Metals"="Metals",
  "Industry_and_manufacture-Mining_and_quarrying"="Mining&Quarrying",
  "Industry_and_manufacture-Potteries"="Potteries",
  "Industry_and_manufacture-Print"="Print",
  "Industry_and_manufacture-Steam_and_engines"="Steam&Engines",
  "Industry_and_manufacture-Textiles"="Textiles",
  "Industry_and_manufacture-Mixed"="Mixed",
  "Industry_and_manufacture-Other"="Other",
  "Leisure_and_sport-Cricket"="Cricket",
  "Leisure_and_sport-Fairgrounds_and_amusements"="Fairgrounds&Amusements",
  "Leisure_and_sport-Film_Cinema_and_TV"="Film,Cinema,TV",
  "Leisure_and_sport-Rugby_and_football"="Rugby&Football",
  "Leisure_and_sport-Toys_and_models"="Toys&Models",
  "Leisure_and_sport-Other"="Other",
  "Medicine_and_health-Hospital"="Hospital",
  "Medicine_and_health-Professional_association"="Prof. Assoc.",
  "Medicine_and_health-Other"="Other",
  "Natural_world-Dinosaurs"="Dinosaurs",
  "Natural_world-Fossils"="Fossils",
  "Natural_world-Geology"="Geology",
  "Natural_world-Herbaria_and_gardening"="Herbaria&Gardening",
  "Natural_world-Zoology"="Zoology",
  "Natural_world-Mixed"="Mixed",
  "Natural_world-Other"="Other",
  "Personality-Art"="Art",
  "Personality-Explorer"="Explorer",
  "Personality-Literary"="Literary",
  "Personality-Music"="Music",
  "Personality-Political"="Political",
  "Personality-Religious"="Religious",
  "Personality-Scientific"="Scientific",
  "Personality-Other"="Other",
  "Rural_Industry-Farming"="Farming",
  "Rural_Industry-Forges"="Forges",
  "Rural_Industry-Rural_life"="Rural Life",
  "Rural_Industry-Textiles"="Textiles",
  "Rural_Industry-Watermills"="Watermills",
  "Rural_Industry-Windmills"="Windmills",
  "Rural_Industry-Other"="Other",
  "Science_and_technology-Computing_and_gaming"="Computing&Gaming",
  "Science_and_technology-Other"="Other",
  "Sea_and_seafaring-Boats_and_ships"="Boats&Ships",
  "Sea_and_seafaring-Fishing"="Fishing",
  "Sea_and_seafaring-Lighthouses"="Lighthouses",
  "Sea_and_seafaring-Mixed"="Mixed",
  "Sea_and_seafaring-Other"="Other",
  "Services-Fire"="Fire",
  "Services-Police"="Police",
  "Services-RNLI"="RNLI",
  "Services-Other"="Other",
  "Transport-Aviation"="Aviation",
  "Transport-Bicycles"="Bicycles",
  "Transport-Buses_and_trams"="Buses&Trams",
  "Transport-Canals"="Canals",
  "Transport-Cars_and_motorbikes"="Cars&Motorbikes",
  "Transport-Trains_and_railways"="Trains&Railways",
  "Transport-Mixed"="Mixed",
  "Transport-Other"="Other",
  "Utilities-Gas_and_electricity"="Gas&Electric",
  "Utilities-Water_and_waste"="Water&Waste",
  "War_and_conflict-Airforce"="Airforce",
  "War_and_conflict-Bunker"="Bunker",
  "War_and_conflict-Castles_and_forts"="Castles&Forts",
  "War_and_conflict-Event_or_site"="Event/Site",
  "War_and_conflict-Military"="Military",
  "War_and_conflict-Navy"="Navy",
  "War_and_conflict-Regiment"="Regiment",
  "War_and_conflict-Other"="Other",
  "Mixed-Bygones"="Bygones",
  "Mixed-Encyclopaedic"="Encyclopaedic",
  "Mixed-Other"="Other",
  # recipient outcome
  "mostly NA"="mostly NA",
  "mostly civic organisation"="mostly civic organisation",
  "mostly museum/library/archive"="mostly museum/library/archive",
  "mostly museum"="mostly museum",
  "mostly trader"="mostly trader",
  "mostly individual"="mostly individual",
  "mostly unknown"="mostly unknown",
  # event outcome
  "mostly left"="mostly left",
  "mostly kept"="mostly kept",
  "mostly stored"="mostly stored",
  "mostly moved"="mostly moved",
  "mostly returned"="mostly returned",
  "mostly transferred"="mostly transferred",
  "mostly sold"="mostly sold",
  "mixed"="mixed",
  # reason for closure
  "other"="other",
  "financial"="financial",
  "low visitor numbers"="low visitors",
  "loss of premises"="loss premises",
  "destruction"="destruction",
  "collections"="collections",
  "building"="building",
  "strategic closure"="strategic",
  "restructure of host organisation"="restructure of host",
  "dispute"="dispute",
  "life events"="life events",
  "staff"="staff"
)

very_short_labels <- c(
  "All"="All",
  # size
  "unknown"="U",
  "small"="S",
  "medium"="M",
  "large"="L",
  "huge"="H",
  # governance
  "Unknown"="Unk",
  "Private"="Prv",
  "Independent"="Ind",
  "Independent-Not_for_profit"="NProf",
  "Independent-National_Trust_for_Scotland"="NTS",
  "Independent-National_Trust"="NT",
  "Independent-English_Heritage"="EH",
  "Independent-Historic_Environment_Scotland"="HES",
  "University"="Uni",
  "National"="Nat",
  "Local_Authority"="LocA",
  "Other_Government"="OGov",
  # country / region
  "Isle of Man"="IoM",
  "Channel Islands"="CI",
  "Northern Ireland"="NI",
  "Wales"="Wal",
  "Scotland"="Sco",
  "England"="En",
  "North East (English Region)"="NE",
  "North West (English Region)"="NW",
  "Yorkshire and The Humber (English Region)"="Y&H",
  "East Midlands (English Region)"="EM",
  "West Midlands (English Region)"="WM",
  "South East (English Region)"="SE",
  "South West (English Region)"="SW",
  "East of England (English Region)"="EE",
  "London (English Region)"="Lon",
  # accreditation
  "Accredited"="Acc",
  "Unaccredited"="Unac",
  # subject matter
  "War_and_conflict"="W&C",
  "Utilities"="Ut",
  "Transport"="Trn",
  "Services"="Srv",
  "Sea_and_seafaring"="Sea",
  "Science_and_technology"="S&T",
  "Rural_Industry"="RI",
  "Personality"="Prs",
  "Other"="Oth",
  "Natural_world"="NW",
  "Mixed"="Mxd",
  "Medicine_and_health"="M&H",
  "Local_Histories"="LH",
  "Leisure_and_sport"="L&S",
  "Industry_and_manufacture"="I&M",
  "Food_and_drink"="F&D",
  "Communications"="Com",
  "Buildings"="Bld",
  "Belief_and_identity"="B&I",
  "Arts"="Art",
  "Archaeology"="Arc",
  # subject matter full
  "Archaeology-Greek_and_Egyptian"="Gr./Egpt",
  "Archaeology-Medieval"="Mediev.",
  "Archaeology-Prehistory"="Prehist.",
  "Archaeology-Roman"="Roman",
  "Archaeology-Mixed"="Mixed",
  "Archaeology-Other"="Other",
  "Arts-Ceramics"="Ceram.",
  "Arts-Costume_and_textiles"="Cost./Textil",
  "Arts-Crafts"="Crafts",
  "Arts-Design"="Design",
  "Arts-Fine_and_decorative_arts"="Fine/Decor.",
  "Arts-Glass"="Glass",
  "Arts-Literature"="Lit.",
  "Arts-Music"="Music",
  "Arts-Photography"="Photo.",
  "Arts-Other"="Other",
  "Belief_and_identity-Church_treasuries"="Ch.Treas.",
  "Belief_and_identity-Ethnic_group"="Ethnic",
  "Belief_and_identity-Freemasons"="Freemas.",
  "Belief_and_identity-Religion"="Religion",
  "Belief_and_identity-Religious_buildings"="Rel.Blds",
  "Belief_and_identity-Other"="Other",
  "Buildings-Civic"="Civic",
  "Buildings-Houses-Large_houses"="House(L)",
  "Buildings-Houses-Medium_houses"="House(M)",
  "Buildings-Houses-Small_houses"="House(S)",
  "Buildings-Palace"="Palace",
  "Buildings-Penal"="Penal",
  "Buildings-School"="School",
  "Buildings-Shops"="Shops",
  "Buildings-Other"="Other",
  "Communications-Post"="Post",
  "Communications-Radio"="Radio",
  "Communications-Other"="Other",
  "Industry_and_manufacture-Clocks_and_watches"="Clock/Watch",
  "Industry_and_manufacture-Industrial_life"="Indust.Life",
  "Industry_and_manufacture-Metals"="Metals",
  "Industry_and_manufacture-Mining_and_quarrying"="Mine/Quarry",
  "Industry_and_manufacture-Potteries"="Pottery",
  "Industry_and_manufacture-Print"="Print",
  "Industry_and_manufacture-Steam_and_engines"="Steam/Eng",
  "Industry_and_manufacture-Textiles"="Textiles",
  "Industry_and_manufacture-Mixed"="Mixed",
  "Industry_and_manufacture-Other"="Other",
  "Leisure_and_sport-Cricket"="Cricket",
  "Leisure_and_sport-Fairgrounds_and_amusements"="Fair/Amusem",
  "Leisure_and_sport-Film_Cinema_and_TV"="Film/Cin/TV",
  "Leisure_and_sport-Rugby_and_football"="Rugby&Foot",
  "Leisure_and_sport-Toys_and_models"="Toys/Models",
  "Leisure_and_sport-Other"="Other",
  "Medicine_and_health-Hospital"="Hospital",
  "Medicine_and_health-Professional_association"="Prof.Assoc.",
  "Medicine_and_health-Other"="Other",
  "Natural_world-Dinosaurs"="Dino",
  "Natural_world-Fossils"="Foss",
  "Natural_world-Geology"="Geology",
  "Natural_world-Herbaria_and_gardening"="Herb/Garden",
  "Natural_world-Zoology"="Zoology",
  "Natural_world-Mixed"="Mixed",
  "Natural_world-Other"="Other",
  "Personality-Art"="Art",
  "Personality-Explorer"="Expl.",
  "Personality-Literary"="Lit.",
  "Personality-Music"="Music",
  "Personality-Political"="Polit.",
  "Personality-Religious"="Relig.",
  "Personality-Scientific"="Sci.",
  "Personality-Other"="Other",
  "Rural_Industry-Farming"="Farm",
  "Rural_Industry-Forges"="Forge",
  "Rural_Industry-Rural_life"="RuralLife",
  "Rural_Industry-Textiles"="Textiles",
  "Rural_Industry-Watermills"="Watermill",
  "Rural_Industry-Windmills"="Windmill",
  "Rural_Industry-Other"="Other",
  "Science_and_technology-Computing_and_gaming"="Comput.",
  "Science_and_technology-Other"="Other",
  "Sea_and_seafaring-Boats_and_ships"="Boat/Ship",
  "Sea_and_seafaring-Fishing"="Fish",
  "Sea_and_seafaring-Lighthouses"="Lighths",
  "Sea_and_seafaring-Mixed"="Mixed",
  "Sea_and_seafaring-Other"="Other",
  "Services-Fire"="Fire",
  "Services-Police"="Police",
  "Services-RNLI"="RNLI",
  "Services-Other"="Other",
  "Transport-Aviation"="Aviat.",
  "Transport-Bicycles"="Bicyc.",
  "Transport-Buses_and_trams"="Bus/Tram",
  "Transport-Canals"="Canal",
  "Transport-Cars_and_motorbikes"="Car/Moto",
  "Transport-Trains_and_railways"="Train/Rail",
  "Transport-Mixed"="Mixed",
  "Transport-Other"="Other",
  "Utilities-Gas_and_electricity"="Gas/Elec",
  "Utilities-Water_and_waste"="Water/Waste",
  "War_and_conflict-Airforce"="Airf.",
  "War_and_conflict-Bunker"="Bunker",
  "War_and_conflict-Castles_and_forts"="Castle/Fort",
  "War_and_conflict-Event_or_site"="Event/Site",
  "War_and_conflict-Military"="Mil",
  "War_and_conflict-Navy"="Navy",
  "War_and_conflict-Regiment"="Reg.",
  "War_and_conflict-Other"="Other",
  "Mixed-Bygones"="Bygones",
  "Mixed-Encyclopaedic"="Encyc.",
  "Mixed-Other"="Other",
  # recipient outcome
  "mostly NA"="mostly NA",
  "mostly civic organisation"="mostly civic",
  "mostly museum/library/archive"="mostly m/l/a",
  "mostly museum"="mostly museum",
  "mostly trader"="mostly trader",
  "mostly individual"="mostly indiv",
  "mostly unknown"="mostly unk",
  # event outcome
  "mostly left"="mostly left",
  "mostly kept"="mostly kept",
  "mostly stored"="mostly stored",
  "mostly moved"="mostly moved",
  "mostly returned"="mostly return",
  "mostly transferred"="mostly transf",
  "mostly sold"="mostly sold",
  "mixed"="mixed",
  # reason for closure
  "other"="other",
  "financial"="financial",
  "low visitor numbers"="low visitors",
  "loss of premises"="loss premises",
  "destruction"="destruction",
  "collections"="collections",
  "building"="building",
  "strategic closure"="strategic",
  "restructure of host organisation"="restructure of host",
  "dispute"="dispute",
  "life events"="life events",
  "staff"="staff"
)

museum_attribute_ordering <- c(
  "All",
  # size
  "unknown",
  "small",
  "medium",
  "large",
  "huge",
  # governance
  "Unknown",
  "Private",
  "Independent",
  "Independent-Historic_Environment_Scotland",
  "Independent-National_Trust_for_Scotland",
  "Independent-National_Trust",
  "Independent-English_Heritage",
  "Independent-Not_for_profit",
  "University",
  "Other_Government",
  "Local_Authority",
  "National",
  # region/country
  "Isle of Man",
  "Channel Islands",
  "Northern Ireland",
  "Wales",
  "Scotland",
  "England",
  "North East (English Region)",
  "North West (English Region)",
  "Yorkshire and The Humber (English Region)",
  "East Midlands (English Region)",
  "West Midlands (English Region)",
  "East of England (English Region)",
  "London (English Region)",
  "South East (English Region)",
  "South West (English Region)",
  # accreditation
  "Unaccredited",
  "Accredited",
  # subject
  "Other",
  "Mixed-Other",
  "Mixed-Encyclopaedic",
  "Mixed-Bygones",
  "Mixed",
  "War_and_conflict-Other",
  "War_and_conflict-Regiment",
  "War_and_conflict-Navy",
  "War_and_conflict-Military",
  "War_and_conflict-Event_or_site",
  "War_and_conflict-Castles_and_forts",
  "War_and_conflict-Bunker",
  "War_and_conflict-Airforce",
  "War_and_conflict",
  "Utilities-Water_and_waste",
  "Utilities-Gas_and_electricity",
  "Utilities",
  "Transport-Other",
  "Transport-Mixed",
  "Transport-Trains_and_railways",
  "Transport-Cars_and_motorbikes",
  "Transport-Canals",
  "Transport-Buses_and_trams",
  "Transport-Bicycles",
  "Transport-Aviation",
  "Transport",
  "Services-Other",
  "Services-RNLI",
  "Services-Police",
  "Services-Fire",
  "Services",
  "Sea_and_seafaring-Other",
  "Sea_and_seafaring-Mixed",
  "Sea_and_seafaring-Lighthouses",
  "Sea_and_seafaring-Fishing",
  "Sea_and_seafaring-Boats_and_ships",
  "Sea_and_seafaring",
  "Science_and_technology-Other",
  "Science_and_technology-Computing_and_gaming",
  "Science_and_technology",
  "Rural_Industry-Other",
  "Rural_Industry-Windmills",
  "Rural_Industry-Watermills",
  "Rural_Industry-Textiles",
  "Rural_Industry-Rural_life",
  "Rural_Industry-Forges",
  "Rural_Industry-Farming",
  "Rural_Industry",
  "Personality-Other",
  "Personality-Scientific",
  "Personality-Religious",
  "Personality-Political",
  "Personality-Music",
  "Personality-Literary",
  "Personality-Explorer",
  "Personality-Art",
  "Personality",
  "Natural_world-Other",
  "Natural_world-Mixed",
  "Natural_world-Zoology",
  "Natural_world-Herbaria_and_gardening",
  "Natural_world-Geology",
  "Natural_world-Fossils",
  "Natural_world-Dinosaurs",
  "Natural_world",
  "Medicine_and_health-Other",
  "Medicine_and_health-Professional_association",
  "Medicine_and_health-Hospital",
  "Medicine_and_health",
  "Local_Histories",
  "Leisure_and_sport-Other",
  "Leisure_and_sport-Toys_and_models",
  "Leisure_and_sport-Rugby_and_football",
  "Leisure_and_sport-Film_Cinema_and_TV",
  "Leisure_and_sport-Fairgrounds_and_amusements",
  "Leisure_and_sport-Cricket",
  "Leisure_and_sport",
  "Industry_and_manufacture-Other",
  "Industry_and_manufacture-Mixed",
  "Industry_and_manufacture-Textiles",
  "Industry_and_manufacture-Steam_and_engines",
  "Industry_and_manufacture-Print",
  "Industry_and_manufacture-Potteries",
  "Industry_and_manufacture-Mining_and_quarrying",
  "Industry_and_manufacture-Metals",
  "Industry_and_manufacture-Industrial_life",
  "Industry_and_manufacture-Clocks_and_watches",
  "Industry_and_manufacture",
  "Food_and_drink",
  "Communications-Other",
  "Communications-Radio",
  "Communications-Post",
  "Communications",
  "Buildings-Other",
  "Buildings-Shops",
  "Buildings-School",
  "Buildings-Penal",
  "Buildings-Palace",
  "Buildings-Houses-Small_houses",
  "Buildings-Houses-Medium_houses",
  "Buildings-Houses-Large_houses",
  "Buildings-Civic",
  "Buildings",
  "Belief_and_identity-Other",
  "Belief_and_identity-Religious_buildings",
  "Belief_and_identity-Religion",
  "Belief_and_identity-Freemasons",
  "Belief_and_identity-Ethnic_group",
  "Belief_and_identity-Church_treasuries",
  "Belief_and_identity",
  "Arts-Other",
  "Arts-Photography",
  "Arts-Music",
  "Arts-Literature",
  "Arts-Glass",
  "Arts-Fine_and_decorative_arts",
  "Arts-Design",
  "Arts-Crafts",
  "Arts-Costume_and_textiles",
  "Arts-Ceramics",
  "Arts",
  "Archaeology-Other",
  "Archaeology-Mixed",
  "Archaeology-Roman",
  "Archaeology-Prehistory",
  "Archaeology-Medieval",
  "Archaeology-Greek_and_Egyptian",
  "Archaeology",
  # recipient outcome
  "mostly NA",
  "mostly civic organisation",
  "mostly museum/library/archive",
  "mostly museum",
  "mostly trader",
  "mostly individual",
  "mostly unknown",
  # event outcome
  "mostly left",
  "mostly kept",
  "mostly stored",
  "mostly moved",
  "mostly returned",
  "mostly transferred",
  "mostly sold",
  "mixed",
  # reason for closure
  "other",
  "financial",
  "low visitor numbers",
  "loss of premises",
  "destruction",
  "collections",
  "building",
  "strategic closure",
  "restructure of host organisation",
  "dispute",
  "life events",
  "staff"
)

collection_status_labels <- data.frame(
  internal_label=c("collection", "loan", "handling", "museum-stuff"),
  tidy_label=c("Items from a museum's collection", "Items loaned to a museum", "Items for handling", "Other items (e.g. furniture)"),
  default_filter=c(TRUE, FALSE, FALSE, FALSE)
)
